#!/bin/bash

echo Installing the script.

mkdir -p /etc/rc.d && echo "launchctl unload /System/Library/LaunchDaemons/com.apple.nfcd.plist" > /etc/rc.d/unloadNfcd && chmod 777 /etc/rc.d/unloadNfcd

echo INSTALLED SUCCESSFULLY. 

echo Unloading the daemon. 

cd /etc/rc.d
bash unloadNfcd

echo DONE!

echo /u/dpkg_ says hi

exit 0