#!/bin/bash

echo Installing the script.

mkdir -p /etc/rc.d && echo "launchctl unload /System/Library/LaunchDaemons/com.apple.tipsd.plist" > /etc/rc.d/unloadTipsd && chmod 777 /etc/rc.d/unloadTipsd

echo INSTALLED SUCCESSFULLY. 

echo Unloading the daemon. 

cd /etc/rc.d
bash unloadTipsd

echo DONE!

echo /u/dpkg_ says hi

exit 0